export function cleanReportText(text: string): string {
  if (!text) return ''

  return text
    .replace(/^🎵\s*Sobre\s*"[^"]*"\s*\n*/i, '')
    .replace(/^🎵\s*About\s*"[^"]*"\s*\n*/i, '')
    .replace(/^Puntuación:\s*\d+\/100\s*\n*/im, '')
    .replace(/^Score:\s*\d+\/100\s*\n*/im, '')
    .replace(/^Puntuación MR:\s*\d+\/100\s*\n*/im, '')
    .replace(/^MR Score:\s*\d+\/100\s*\n*/im, '')
    .replace(/^Veredicto:\s*[^\n]+\s*\n*/im, '')
    .replace(/^Verdict:\s*[^\n]+\s*\n*/im, '')
    .replace(/[═─━_]{3,}/g, '')
    .replace(/^[═─━_\s]+$/gm, '')
    .replace(/[═─━]{2,}/g, '')
    .replace(/(?<!✅\s)ASPECTOS POSITIVOS/g, '✅ Aspectos Positivos')
    .replace(/(?<!✅\s)POSITIVE ASPECTS/g, '✅ Positive Aspects')
    .replace(/(?<!⚠️\s)ASPECTOS PARA REVISAR/g, '⚠️ Aspectos para Revisar')
    .replace(/(?<!⚠️\s)AREAS TO REVIEW/g, '⚠️ Areas to Review')
    .replace(/(?<!⚠️\s)ÁREAS A MEJORAR/g, '⚠️ Áreas a Mejorar')
    .replace(/(?<!⚠️\s)AREAS TO IMPROVE/g, '⚠️ Areas to Improve')
    .replace(/(?<!⚠️\s)SI ESTE ARCHIVO CORRESPONDE A UNA MEZCLA:/g, '⚠️ Si este archivo corresponde a una mezcla:')
    .replace(/(?<!⚠️\s)IF THIS FILE IS A MIX:/g, '⚠️ If this file is a mix:')
    .replace(/(?<!✅\s)SI ESTE ES TU MASTER FINAL:/g, '✅ Si este es tu master final:')
    .replace(/(?<!✅\s)IF THIS IS YOUR FINAL MASTER:/g, '✅ If this is your final master:')
    .replace(/^✓\s*/gm, '• ')
    .replace(/^→\s*/gm, '• ')
    .replace(/✅\s*✅/g, '✅')
    .replace(/⚠️\s*⚠️/g, '⚠️')
    .replace(/\n*💡\s*Recomendaci[óo]n:[^\n]*/g, '')
    .replace(/\n*💡\s*Recommendation:[^\n]*/g, '')
    .replace(/\n*Recomendaci[óo]n:[^\n]*/g, '')
    .replace(/\n*Recommendation:[^\n]*/g, '')
    .replace(/\n*📊\s*An[áa]lisis realizado[^\n]*/gu, '')
    .replace(/\n*📊\s*Analysis performed[^\n]*/gu, '')
    .replace(/\n*[🎧🔧🔍💬]\s*(Tu mezcla|Your mix|Escr[íi]benos|Write us|No recomiendo|I don't recommend|Enviarlo|Sending it|Hay aspectos|There are|Hay decisiones|Hay problemas|No significa|Está técnicamente)[^\n]*/gu, '')
    .replace(/\n*[🎧🔧🔍💬][^\n]*/gu, '')
    .replace(/\n*[^\n]*(escr[íi]benos|write us)[^\n]*/gi, '')
    .replace(/^\s*[\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}]\s*$/gmu, '')
    .replace(/[\uD800-\uDFFF]/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .split('\n')
    .map(line => line.trim())
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}
